apiVersion: auth.consul.hashicorp.com/v2beta1
kind: TrafficPermissions
metadata:
  name: client-to-server
spec:
  destination:
    identityName: static-server
  action: ACTION_ALLOW
  permissions:
  - sources:
    - partition: default
    destinationRules:
    - portNames:
      - web
