apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-client
  labels:
    app: static-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-client
  template:
    metadata:
      labels:
        app: static-client
    spec:
      serviceAccountName: static-client
      containers:
      - name: static-client
        image: curlimages/curl
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep infinity']
        resources:
          limits:
            cpu: 700m
            memory: 500Mi

