---
apiVersion: v1
kind: Service
metadata:
  name: test-job
  namespace: default
  labels:
    app: test-job
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: test-job
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-job
automountServiceAccountToken: true
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: test-job
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        command: ["sleep", "30"]
      restartPolicy: OnFailure
