global:
  image: ttl.sh/dans/consul-dev-access-logs:24h
  imageK8S: ttl.sh/dans/consul-k8s-dev-access-logs:24h
  imageConsulDataplane: ttl.sh/dans/consul-dataplane-test-001:24h
  name: consul
  datacenter: dc1
  # # The main enabled/disabled setting.
  # # If true, servers, clients, Consul DNS and the Consul UI will be enabled.
  # enabled: true
  # # Enables TLS across the cluster to verify authenticity of the Consul servers and clients.
  # tls:
  #   enabled: true
  # # Enables ACLs across the cluster to secure access to data and APIs.
  # acls:
  #   # If true, automatically manage ACL tokens and policies for all Consul components.
  #   manageSystemACLs: true
server:
  enabled: true
  replicas: 1
ui:
  enabled: true
  port:
    http: 80
    https: 443
  service:
    type: ClusterIP
connectInject:
  enabled: true
  default: true
  transparentProxy:
    defaultEnabled: true
  # envoyExtraArgs: "--log-level trace"
# apiGateway:
#   enabled: true
#   image: "hashicorp/consul-api-gateway:0.5.1"
#   logLevel: trace
#   managedGatewayClass:
#     serviceType: NodePort
#     useHostPorts: true
# # The following Node selectors are hack to make sure we bind the right container to the host.
# # You'll need to do something different here for KIND.
#     nodeSelector: |
#       kubernetes.io/hostname: k3d-access-logs-testing-agent-0
#   controller:
#     nodeSelector: |
#       kubernetes.io/hostname: k3d-access-logs-testing-agent-0
