global:
  name: consul
  image: hashicorppreview/consul:1.17.0
  imageK8S: hashicorppreview/consul-k8s-control-plane:1.3.0
  imageConsulDataplane: hashicorppreview/consul-dataplane:1.3.0
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
  experiments: ["resource-apis"]
ui:
  enabled: false
server:
  enabled: true
  replicas: 1
connectInject:
  default: true
  transparentProxy:
    defaultEnabled: true

